name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["Bug"]
assignees:
  - displayk
body:
  - type: dropdown
    id: dbdversion
    attributes:
      label: What version of DBD are you using?
      multiple: false
      options:
        - 5.7.2
        - 5.6.2
  - type: input
    id: modversion
    attributes:
      label: Console Mod Version
      description: What version of the console mod are you using?
      placeholder: ex. 2.1.3
     validations:
      required: true
  - type: textarea
    id: issuedesc
    attributes:
      label: Issue Description
      description: Describe the issue.
      placeholder: ...
      value: "..."
    validations:
      required: true
