#pragma once

#include "CoreMinimal.h"
#include "EContext.generated.h"

UENUM(BlueprintType)
enum class EContext : uint8
{
	None,
	ArchiveIntro,
	ArchiveMenu,
	ArchivePastStories,
	ArchiveRewards,
	ArchiveStory,
	ArchiveCompendium,
	ArchiveRift,
	ArchiveTome,
	BloodWeb,
	Character,
	Consent,
	Credits,
	Customization,
	GameFlowOff,
	Hud,
	Inbox,
	LightSensitivity,
	Loading,
	Loadout,
	Lobby,
	LobbyOff,
	MainMenu,
	Onboarding,
	RoleSelection,
	SpecialEventLoading,
	Spectate,
	Splash,
	Store,
	Tally,
	Tutorial,
	AccountLinkPopup,
	ArchivePassPurchasePopup,
	ArchiveTierPurchasePopup,
	CrowdChoiceTugOfWarPopup,
	DailyRewardsPopup,
	EventEntryPopup,
	FearMarketPopup,
	FriendSearchPopup,
	GenericPopup,
	GenericTextInputPopup,
	NewContentPopup,
	ProcessingPopup,
	ReportPlayerPopup,
	SeasonEndPopup,
	SeasonEndRankRewardsPopup,
	UnlockPersonalPerksPopup,
	LoadoutMenuPopup,
	UMGEventEntryPopup,
	UMGFearMarketPopup,
	UMGGenericPopup,
	UMGUnlockPersonalPerksPopup,
	Count,
};
