#include "HasTokenOrCooldownTimerRemainingActivationElapsedIconStrategy.h"

UHasTokenOrCooldownTimerRemainingActivationElapsedIconStrategy::UHasTokenOrCooldownTimerRemainingActivationElapsedIconStrategy()
{

}
